export const Message = {
    TOKEN: {
        SUCCESS_REFRESH: "Làm mới token thành công",
        FAIL: "Token không hợp lệ",
        FAIL_KEY: "Khóa không đúng",
        FAIL_EXPIRED: "Token hết hạn",
        FAIL_MISSING: "Không có token",
    },
    LOGIN: {
        SUCCESS: "Đăng nhập thành công",
        FAIL: "Đăng nhập thất bại",
        PW_FAIL: "Mật khẩu không đúng",
        EMAIL_FAIL: "Email không đúng",
    },
    REGISTER: {
        SUCCESS: "Đăng ký thành công",
        FAIL: "Đăng ký",
        EMAIL_FAIL: "Email đã tồn tại",
    },
    COMMENT: {
        LIST_ALL: "Danh sách bình luận",
        SUCCESS: "Đã bình luận",
    },
    IMAGE: {
        LIST_ALL: "Danh sách tất cả hình ảnh",
        LIST_SEARCH: "Danh sách tìm kiếm hình ảnh",
        LIST_UPLOAD: "Danh sách hình ảnh người dùng đã đăng",
        LIST_SAVE: "Danh sách hình đã lưu",
        DETAIL: "Chi tiết hình ảnh",
        SAVED: "Đã lưu",
        UNSAVED: "Bỏ lưu",
        NOTSAVED: "Chưa lưu",
        DELETE_FAIL_INVALID: "Xóa thất bại, không tìm thấy hình",
        DELETE_FAIL_UNAUTHORIZED: "Người dùng không có quyền xóa hình ảnh này",
        DELETE_SUCESS: "Xóa thành công",
        UPLOAD_SUCCESS: "Đăng hình thành công",
        NOT_FOUND: "Không tìm thấy hình ảnh",
    },
    USER: {
        SUCCESS: "Lấy thông tin người dùng thành công",
        NOT_FOUND: "Không tìm thấy người dùng",
        UPDATE_INFO_SUCCESS: "Cập nhật thông tin tài khoản thành công",
        UPDATE_INFO_FAIL_UNAUTHORIZED: "Cập nhật thất bại, vai trò không được phép truy cập tài nguyên",
        UPDATE_PASSWORD_SUCCESS: "Thay đổi mật khẩu thành công",
        UPDATE_PASSWORD_FAIL_INCORRECT: "Thay đổi mật khẩu thất bại",
        UPDATE_AVATAR_SUCCESS: "Thay đổi ảnh đại diện thành công",
        UNAUTHORIZED: "Vai trò không được phép truy cập tài nguyên",
        DELETE_SUCCESS: "Xóa tài khoản thành công",
        FAIL_PAGEINDEX: "PageIndex vượt quá số trang có thể có"
    },
}